CREATE DATABASE IF NOT EXISTS BIBLIOTECA_MULTIPLA;

USE BIBLIOTECA_MULTIPLA;

CREATE TABLE IF NOT EXISTS CATEGORIA(
ID INT AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
PRIMARY KEY(ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ANIMACAO(
ID INT AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
ANO_DE_LANCAMENTO INT,
GENERO VARCHAR(300),
NUMERO_EPISODIOS INT UNSIGNED,
CATEGORIA_ID INT,
DATA_DE_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ASSISTIDO BIT(1) DEFAULT 0,
PRIMARY KEY (ID),
CONSTRAINT CATEGORIA_FK FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS ANIMACAO_N_ASSISTIDO (
ANIMACAO_ID INT NOT NULL,
RELEVANCIA ENUM('S', 'A', 'B', 'C', 'D'),
PRIORIDADE ENUM('--', '-', '=', '+', '++'),
PRIMARY KEY (ANIMACAO_ID),
CONSTRAINT FK_ANIMACAO_N_A FOREIGN KEY (ANIMACAO_ID) REFERENCES ANIMACAO (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ANIMACAO_ASSISTIDO (
ANIMACAO_ID INT NOT NULL,
DATA_DE_FINALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
NOTA DECIMAL (5,3),
PRIMARY KEY (ANIMACAO_ID),
CONSTRAINT FK_ANIMACAO_A FOREIGN KEY (ANIMACAO_ID) REFERENCES ANIMACAO (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DUBLADOR (
ID INT AUTO_INCREMENT,
NOME VARCHAR(50),
NASCIMENTO DATE,
PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PERSONAGEM (
ID INT AUTO_INCREMENT,
NOME VARCHAR(50),
ANIMACAO_ID INT NOT NULL,
DUBLADOR_ID INT NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT FK_ANIMACAO_PERSONAGEM FOREIGN KEY (ANIMACAO_ID) REFERENCES ANIMACAO (ID),
CONSTRAINT FK_DUBLADOR FOREIGN KEY (DUBLADOR_ID) REFERENCES DUBLADOR (ID)
) ENGINE = InnoDB;

INSERT INTO `biblioteca_multipla`.`categoria`
(`NOME`)
VALUES
('ANIMACAO ORIENTAL'),
('ANIMACAO_OCIDENTAL'),
('SERIADO'),
('FILME'),
('JOGO_ELETRONICO');

DELIMITER //

CREATE PROCEDURE ANIMACAO_N_ASSISTIDO_INSERCAO (cNOME VARCHAR (100), cANO_DE_LANCAMENTO INT, cGENERO VARCHAR(250), cNUMERO_EPISODIOS INT, cCATEGORIA_ID INT, cRELEVANCIA ENUM('S', 'A', 'B', 'C', 'D'), cPRIORIDADE ENUM('--', '-', '=', '+', '++'))
BEGIN
	INSERT INTO ANIMACAO (ID, NOME, ANO_DE_LANCAMENTO, GENERO, NUMERO_EPISODIOS, CATEGORIA_ID, DATA_DE_REGISTRO, ASSISTIDO) VALUES (DEFAULT, cNOME, cANO_DE_LANCAMENTO, cGENERO, cNUMERO_EPISODIOS, cCATEGORIA_ID, default, default);
	INSERT INTO ANIMACAO_N_ASSISTIDO (ANIMACAO_ID, RELEVANCIA, PRIORIDADE) VALUES ((SELECT MAX(ID) FROM ANIMACAO), cRELEVANCIA, cPRIORIDADE);
END//

CREATE PROCEDURE ANIMACAO_ASSISTIDO_INSERCAO (cNOME VARCHAR (100), cANO_DE_LANCAMENTO INT, cGENERO VARCHAR(250), cNUMERO_EPISODIOS INT, cCATEGORIA_ID INT, cNOTA DECIMAL (5,3))
BEGIN
	INSERT INTO ANIMACAO (ID, NOME, ANO_DE_LANCAMENTO, GENERO, NUMERO_EPISODIOS, CATEGORIA_ID, DATA_DE_REGISTRO, ASSISTIDO) VALUES (DEFAULT, cNOME, cANO_DE_LANCAMENTO, cGENERO, cNUMERO_EPISODIOS, cCATEGORIA_ID, default, 1);
    INSERT INTO ANIMACAO_ASSISTIDO (ANIMACAO_ID, DATA_DE_FINALIZACAO, NOTA) VALUES ((SELECT MAX(ID) FROM ANIMACAO), DEFAULT, cNOTA);
END//

CREATE PROCEDURE TERMINA_ANIMACAO (cID INT, cNOTA DECIMAL (5,3))
BEGIN
	DELETE FROM ANIMACAO_N_ASSISTIDO WHERE ANIMACAO_ID = cID;
    INSERT INTO ANIMACAO_ASSISTIDO (ANIMACAO_ID, DATA_DE_FINALIZACAO, NOTA) VALUES (cID, DEFAULT, cNOTA);
    UPDATE ANIMACAO SET ASSISTIDO = 1 WHERE ID = cID;
END//

DELIMITER ;

CALL ANIMACAO_ASSISTIDO_INSERCAO ('He-Man and the Masters of the Universe', 1983, 'Ação/aventura, fantasia científica', 130, 2, 8.5);
CALL ANIMACAO_ASSISTIDO_INSERCAO('Digimon Adventure', 1999, 'Action, Adventure, Comedy, Fantasy', 54, 1, 7.5);
CALL ANIMACAO_N_ASSISTIDO_INSERCAO ('SpongeBob SquarePants', 1999, 'aventura, comédia', 387, 2, 'S', '++');
CALL ANIMACAO_N_ASSISTIDO_INSERCAO('Naruto', 2002, 'Action, Adventure, Comedy', 220, 1, 'C', '+');

INSERT INTO `biblioteca_multipla`.`dublador`
(`ID`, `NOME`, `NASCIMENTO`)
VALUES
(DEFAULT, 'Junko Takeuchi', '1972-04-05'),
(DEFAULT, 'John Erwin', '1936-12-05'),
(DEFAULT, 'Tom Kenny', '1962-07-13');


INSERT INTO `biblioteca_multipla`.`personagem`
(`ID`,
`NOME`,
`ANIMACAO_ID`,
`DUBLADOR_ID`)
VALUES
(DEFAULT, 'Naruto Uzumaki', 4, 1),
(DEFAULT, 'Gomamon', 2, 1),
(DEFAULT, 'He-Man', 1, 2),
(DEFAULT, 'Bob Esponja', 3, 3);